name: Compile slides

on:
  # Run CI on pushes to the main branch
  push:
    branches:
      - main
    paths:
      - "slides/**"
  # Run CI on all pull requests to the main branch
  pull_request:
    branches:
      - main
    paths:
      - "slides/**"
  # Run CI upon manual triggers through the 'Actions' tab of the Github UI
  workflow_dispatch:

jobs:
  build-document:
    name: Install Typst, compile and upload document
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Typst
        uses: typst-community/setup-typst@v5

      - name: Compile Typst script
        run: |
          typst compile --root . slides/ssc-pbp-course.typ
          typst compile --root . slides/prerequisites.typ

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v7
        with:
          name: compiled-pdf
          path: |
            slides/ssc-pbp-course.pdf
            slides/prerequisites.pdf
